// Map legend (one character per 1 m cell; row 0 is the far side of the room):
//   .  floor          #  wall              _  pit (void)       1-3  raised block
//   S  start          G  goal portal       *  checkpoint       ^    spikes
//   a-f pressure plate   A-F door (opens when every plate/terminal with its letter is active)
//   ?  quiz terminal (door letter listed in `terminals`, in reading order)
//   > < v m  laser emitter shooting right / left / toward camera / away
// `heights` (optional) sets the floor height of each cell with digits.
// `par` = deaths allowed for 3 stars. `maxEchoes` = Echoes kept before the oldest shatters.

export const LEVELS = [
  {
    name: 'First Steps',
    par: 0,
    maxEchoes: 3,
    hint: 'Move with WASD / Arrow keys and jump with SPACE. Hop over the blocks and reach the glowing portal.',
    map: [
      '#######',
      '#..G..#',
      '#.....#',
      '#11111#',
      '#.....#',
      '#.....#',
      '#..S..#',
      '#######',
    ],
  },
  {
    name: 'Leave a Mark',
    par: 1,
    maxEchoes: 3,
    hint: 'Door A only opens while plate A is held. Stand on the plate and press R: your Echo keeps holding it for you.',
    map: [
      '#########',
      '#...G...#',
      '#.......#',
      '####A####',
      '#.......#',
      '#.a...S.#',
      '#.......#',
      '#########',
    ],
  },
  {
    name: 'Stepping Stone',
    par: 1,
    maxEchoes: 3,
    hint: 'That ledge is too high to jump. Press R right next to it: your Echo becomes a step. Jump on it, then onto the ledge.',
    map: [
      '#######',
      '#..G..#',
      '#.....#',
      '#.....#',
      '#.....#',
      '#.....#',
      '#..S..#',
      '#######',
    ],
    heights: [
      '0000000',
      '0222220',
      '0222220',
      '0000000',
      '0000000',
      '0000000',
      '0000000',
      '0000000',
    ],
  },
  {
    name: 'Quiz Gate',
    par: 0,
    maxEchoes: 3,
    terminals: ['B', 'A'],
    hint: 'Quiz terminals unlock the door with the same color. Walk up to one and press E. A wrong answer zaps you and leaves an Echo.',
    map: [
      '#########',
      '#...G...#',
      '#.......#',
      '####B####',
      '#.?.....#',
      '#.......#',
      '####A####',
      '#.....?.#',
      '#...S...#',
      '#########',
    ],
  },
  {
    name: 'Spike Bridge',
    par: 2,
    maxEchoes: 4,
    hint: 'Spikes are deadly, but Echoes stand on them just fine. Build a bridge out of your failures and hop across.',
    map: [
      '#######',
      '#..G..#',
      '#.....#',
      '#^^^^^#',
      '#^^^^^#',
      '#^^^^^#',
      '#^^^^^#',
      '#.....#',
      '#..S..#',
      '#######',
    ],
  },
  {
    name: 'Laser Curtain',
    par: 2,
    maxEchoes: 4,
    hint: 'Laser curtains are too tall to jump. An Echo standing in the beam blocks it, so walk through its shadow.',
    map: [
      '#########',
      '#...G...#',
      '#.......#',
      '>.......#',
      '#.......#',
      '#.......#',
      '#.......<',
      '#.......#',
      '#...S...#',
      '#########',
    ],
  },
  {
    name: 'Double Trouble',
    par: 2,
    maxEchoes: 2,
    hint: 'Door A needs BOTH plates held. You can only keep 2 Echoes here: make a third and the oldest shatters. Press X to shatter your newest Echo.',
    map: [
      '###########',
      '#....G....#',
      '#.........#',
      '#####A#####',
      '#a.......a#',
      '#.........#',
      '#....S....#',
      '###########',
    ],
  },
  {
    name: 'Laser Lock',
    par: 1,
    maxEchoes: 3,
    hint: 'The plate sits right inside the laser. Sometimes one failure solves two problems.',
    map: [
      '#########',
      '#...G...#',
      '#.......#',
      '####A####',
      '#.......#',
      '>...a...#',
      '#.......#',
      '#...S...#',
      '#########',
    ],
  },
  {
    name: 'Brain Maze',
    par: 1,
    maxEchoes: 3,
    terminals: ['D', 'C', 'B', 'A'],
    hint: 'Four quiz gates. The last door needs its terminal solved AND its plate held. The glowing ring is a checkpoint.',
    map: [
      '#########',
      '#...G...#',
      '#.......#',
      '####D####',
      '#d.....?#',
      '#...*...#',
      '####C####',
      '#?......#',
      '###B#####',
      '#.....?.#',
      '#.......#',
      '#####A###',
      '#?......#',
      '#...S...#',
      '#########',
    ],
  },
  {
    name: 'Higher Ground',
    par: 1,
    maxEchoes: 3,
    hint: 'Echoes can stand on blocks and on each other. Climb the low block, leave an Echo on it, and use it to reach the top.',
    map: [
      '#######',
      '#..G..#',
      '#.....#',
      '#.11..#',
      '#.....#',
      '#.....#',
      '#..S..#',
      '#######',
    ],
    heights: [
      '0000000',
      '0333330',
      '0333330',
      '0000000',
      '0000000',
      '0000000',
      '0000000',
      '0000000',
    ],
  },
  {
    name: 'Echo Chamber',
    par: 4,
    maxEchoes: 5,
    terminals: ['B'],
    hint: 'Everything you have learned. Laser, plate, spikes, quiz and a high ledge: every failure is a tool.',
    map: [
      '#########',
      '#...G...#',
      '#.......#',
      '####B####',
      '#?....*.#',
      '#.......#',
      '#^^^^^^^#',
      '#^^^^^^^#',
      '#^^^^^^^#',
      '#^^^^^^^#',
      '#.......#',
      '####A####',
      '#.......#',
      '>...a...#',
      '#.......#',
      '#...S...#',
      '#########',
    ],
    heights: [
      '000000000',
      '022222220',
      '000000000',
      '000000000',
      '000000000',
      '000000000',
      '000000000',
      '000000000',
      '000000000',
      '000000000',
      '000000000',
      '000000000',
      '000000000',
      '000000000',
      '000000000',
      '000000000',
      '000000000',
    ],
  },
];
